name: manage-azure-policy-89866bb8
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Stratégie_de_paramétrage_pour_les_stagiaires_04488515-f94d-4dc2-b0e8-ceaf21d5b0c4/**'
#      - .github/workflows/manage-azure-policy-89866bb8.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_89866bb8}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/Stratégie_de_paramétrage_pour_les_stagiaires_04488515-f94d-4dc2-b0e8-ceaf21d5b0c4/**
